# Generated by Django 5.2.5 on 2025-08-25 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingattempt",
            name="subscriber",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="subscriptions.subscriber",
                verbose_name="Подписчик",
            ),
        ),
    ]
