# Generated by Django 5.2.5 on 2025-08-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_of_the_letter", models.CharField(max_length=150)),
                ("letter", models.TextField()),
            ],
        ),
    ]
