# Generated by Django 5.2.5 on 2025-10-10 XX:XX (не трогай эту строку, если она есть)

from django.db import migrations
from django.contrib.auth import get_user_model

User = get_user_model()

def set_owner_to_existing_messages(apps, schema_editor):
    Message = apps.get_model('subscriptions', 'Message')
    # Найти первого суперпользователя или любого пользователя
    owner = User.objects.filter(is_superuser=True).first()
    if not owner:
        owner = User.objects.first()  # Если нет суперпользователя, взять любого
    if owner:
        # Установить owner для всех Message, у которых он None
        updated_count = Message.objects.filter(owner__isnull=True).update(owner=owner)
        print(f"Установлен owner для {updated_count} сообщений.")
    else:
        # Если нет пользователей вообще, удалить старые данные (для чистоты)
        deleted_count = Message.objects.all().delete()[0]
        print(f"Предупреждение: Нет пользователей в базе. Удалено {deleted_count} сообщений.")

def reverse_func(apps, schema_editor):
    # Обратная функция: сбрасываем owner на None (для отката миграции)
    Message = apps.get_model('subscriptions', 'Message')
    Message.objects.all().update(owner=None)
    print("Owner сброшен на None для всех сообщений.")

class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_message_owner'),  # Зависимость от предыдущей миграции (0006)
    ]

    operations = [
        migrations.RunPython(set_owner_to_existing_messages, reverse_func),
    ]
